testenv:
  # DATASET CONFIGURATION
  dataset:

    # Index files (optional - contains list of image paths)
    train_index: "./dataset/deformable_assembly_dataset/train_index.txt"
    test_index: "./dataset/deformable_assembly_dataset/test_index.txt"

    # Dataset format specification
    format: "custom" 
    
    # Data loading configuration
    batch_size: 16
    num_workers: 4
    shuffle: true
    
  # METRICS CONFIGURATION
  metrics:
    # Primary metric: Assembly accuracy
    - name: "assembly_accuracy"
      url: "./testenv/acc.py"
      
    # Additional metrics (optional)
    # - name: "detection_map"
    #   url: "./testenv/detection_metrics.py"
    # - name: "manipulation_success_rate"
    #   url: "./testenv/manipulation_metrics.py"
  
  # Note: Simulation/URDF configs not needed - using Blender-generated dataset
      
  # BENCHMARKING CONFIGURATION
  benchmark:
    # Number of test episodes
    num_episodes: 100
    # Success criteria
    success_threshold: 0.8  # 80% accuracy required for success
    # Timeout settings
    max_episode_length: 500  # Maximum steps per episode
    # Logging
    log_frequency: 10  # Log every N episodes
    save_videos: false
    save_trajectories: true
    
  # RESOURCE LIMITS
  resources:
    # GPU configuration
    gpu_enabled: true
    gpu_device: "cuda:0"
    # Memory limits
    max_memory_mb: 8192
    # Timeout
    max_execution_time_seconds: 3600  