algorithm:
  paradigm_type: "singletasklearning"
  
  name: "assembly_alg_naive"
  description: "Complete assembly pipeline with perception + manipulation"
  
  modules:
    # COMPLETE ASSEMBLY PIPELINE
    # This module orchestrates perception.py + manipulation.py internally
    - name: "assembly_pipeline"
      type: "basemodel"
      url: "testalgorithms/components/naive_assembly_process.py"
      entry_function: "run_complete_pipeline"
      
  hyperparameters:
    # Pipeline mode
    mode: "NAIVE_SETUP"
    
    # Perception hyperparameters
    model_path: "yolov8n.pt"
    conf_threshold: 0.25
    iou_threshold: 0.45
    device: "cpu"
    img_size: 640
    
    # Manipulation hyperparameters
    control_frequency: 100.0
    force_threshold: 50.0
    torque_threshold: 5.0
    gripper_force: 20.0
    
    # Training hyperparameters
    epochs: 100
    batch_size: 16
    learning_rate: 0.001