name: CI

on:
  push:
    branches:
      - main
    tags:
  pull_request:

jobs:
  verify-and-lint:
    runs-on: ubuntu-latest
    name: Verify licenses, do lint
    strategy:
      matrix:
        python-version: [ "3.6", "3.7", "3.8", "3.9", "3.10" ]
    env:
      GOPATH: ${{ github.workspace }}

      # since client-go codegen requires that code checkout GOPATH
      CODE_DIR: '${{github.workspace}}/src/github.com/kubeedge/sedna'

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files '*.py')
